### ISSUE TITLE
Serve up Hello World Page

### ISSUE THREAD

**Issue by ambergkim** [trellistk/trellis-sls-ssr-starter#111]
# Background
We need to make this more generic and have the ability to welcome folks once they get started with this tool.

# What we need to be done.
- [ ] Create a index/hello world page and serve it up in a Lambda.

# Acceptance Criteria
- [ ] If we install this application and run it, when we go in the browser at localhost:8000/ (root route), we get a hello world page)

**Comment by devPalacio** [comment]
I'll take this one

**Comment by devPalacio** [comment]
Done, see #117
