### ISSUE TITLE
CI/CD workflow needs to be updated

### ISSUE THREAD

**Issue by ambergkim** [trellistk/trellis-sls-ssr-starter#118]
**Describe the bug**
This repo used to deploy a web app. It doesn't need to anymore so it should not need to have access to AWS or deploy there either.

**To Reproduce**
When an MR or deploy is run, the pipeline fails because it's looking for AWS access.

**Expected behavior**
CI should only run tests, should not need AWS or SendinBlue access and any lint checks available right now. CD should not try to deploy to AWS.

There's no need to run E2E tests right now either.

**Additional context**
Check the .github folder for workflows.

**Comment by devPalacio** [comment]
Greatly simplified the ci/cd files see #117
